blank_issues_enabled: true
contact_links:
  - name: Github discussions
    url: https://github.com/feldroy/air/discussions
    about: For general discussions.

  - name: Discord server
    url: https://discord.gg/znf8vPsz47
    about: For lightweight questions.

  - name: Documentation
    url: https://docs.airwebframework.org/
    about: Check the documentation
